version: "3"

services:

  sonarqube:
    image: sonarqube:community
    depends_on:
      - db
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://db:5432/sonar
      SONAR_JDBC_USERNAME: sonartest
      SONAR_JDBC_PASSWORD: sonartest
    volumes:
      - SonarQube_data:/opt/SonarQube/data
      - SonarQube_extensions:/opt/SonarQube/extensions
      - SonarQube_logs:/opt/SonarQube/logs
    ports:
      - "8889:9000"

  db:
    image: postgres:12
    environment:
      POSTGRES_USER: sonartest
      POSTGRES_PASSWORD: sonartest
      POSTGRES_DB: sonar  # Create a database named "sonar"
    command: ["postgres", "-c", "log_statement=all"]  # Additional command to create the "sonar" database
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data

volumes:
  SonarQube_data:
  SonarQube_extensions:
  SonarQube_logs:
  postgresql:
  postgresql_data:

